theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.lsp]
display-messages = true

[keys.normal]
"C-r" = [":sh cargo run"]
"D" = ["extend_to_line_bounds", "delete_selection"]
"0" = ["goto_line_start"]
"$" = ["goto_line_end"]

[keys.select]
"D" = ["extend_to_line_bounds", "delete_selection"]
